### ISSUE TITLE
Fatal error durante la generazione delle chiavi

### ISSUE THREAD

**Issue by Sirswatch** [satispay/gbusiness-api-php-sdk#12]
Prima di scriver qui ho passato un giorno a controllare tutto e a rifare decine volte le procedure

1) ho generato un authtoken dall'intefaccia utente
2) ho messo il token nel file /examples/auth-with-token.php
3) faccio la chiamata di questo script
e ricevo sempre un exception error:
Fatal error: Uncaught Exception: Resource not found, request id: zCmOuOQg in /home/webmname/public_html/satispay/lib/Request.php:235 Stack trace: #0 /home/webmname/public_html/satispay/lib/Request.php(50): SatispayGBusiness\Request::request(Array) #1 /home/webmname/public_html/satispay/lib/Api.php(38): SatispayGBusiness\Request::post('/g_business/v1/...', Array) #2 /home/webmname/public_html/satispay/examples/auth-with-token.php(7): SatispayGBusiness\Api::authenticateWithToken('577HPQ') #3 {main} thrown in /home/webmname/public_html/satispay/lib/Request.php on line 235

Dove sbaglio ?

**Comment by Sirswatch** [comment]
Ho capito. Usavo sandbox ma il token è per il sito live :)
Suggerirei agli autori di aggiungere una nota su questo fatto
